# Generated by Django 4.0.4 on 2022-07-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_producto_descripción_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=13, verbose_name='Telefono')),
            ],
        ),
    ]
